### ISSUE TITLE
Missing dependency(?)

### ISSUE THREAD

**Issue by Hades32** [ehazlett/stellar#16]
I wanted to built stellar myself with the built via Docker option (because there are no armhf binaries) and got this

```
-> building daemon e70a943-dev
../../vendor/github.com/mholt/caddy/caddytls/client.go:30:2: cannot find package "github.com/xenolf/lego/acme" in any of:
        /go/src/github.com/ehazlett/stellar/vendor/github.com/xenolf/lego/acme (vendor tree)
        /usr/local/go/src/github.com/xenolf/lego/acme (from $GOROOT)
        /go/src/github.com/xenolf/lego/acme (from $GOPATH)
make: *** [Makefile:50: daemon] Error 1
 -> Built dev version e70a943 (linux/amd64)
```

I now manually added a `go get ...` but now I get

```
# github.com/ehazlett/stellar/vendor/github.com/mholt/caddy/caddytls
../../vendor/github.com/mholt/caddy/caddytls/config.go:122:10: undefined: acme.KeyType
make: *** [Makefile:50: daemon] Error 2
```

**Comment by ehazlett** [comment]
I ran into this a lot with some of the caddy dependencies.  Let me take a look to see if I can reproduce.

**Comment by ehazlett** [comment]
Ok I was able to reproduce and just pushed a quick fix to the docker build dockerfile.  It's not the greatest as the `COPY` busts the go module vendor but once buildkit integration is fully complete we can leverage that for some better caching.  It should be building now (I tested both x86 and arm compiles).  Thanks for reporting!

**Comment by ehazlett** [comment]
ugh I'm getting random failures now as well.  I'm going to re-think the vendoring and see if I can find why `go mod vendor` isn't placing all the needed deps in the local `vendor`.

**Comment by ehazlett** [comment]
OK so some how `vendor/github.com/xenolf/acme` was added as a submodule.  I've fixed it (as well as removed the Go module vendoring for now) so all dependencies should reside in `vendor`.  I also checked on a completely fresh aws instance just to be sure.  Thanks for reporting and sorry for the issues!

**Comment by Hades32** [comment]
Now it works perfectly! Thanks!

What's the reason for using the vendor dir anyway? Why don't you use go modules only?

**Comment by ehazlett** [comment]
@Hades32 the `vendor` dir is for backwards compat (pre-Go module versions) and to be able to build locally in the event of a network failure.  There is also the issue if someone removes a branch or rebases (I've ran into this as well with Go modules).
