### ISSUE TITLE
Volumes ? 

### ISSUE THREAD

**Issue by mabunixda** [ehazlett/stellar#22]
Hi,

i love the idea of a lightweight orchestrator instead of an overblown kubernetes. 
I just created a 2 node cluster within virtual machines to play around if i am able to switch a kubernetes cluster over to stellar.... 
I also ran over #21 :-D but got the example running. 

The mount options is on the same level as docker is using right? Do you have a sample with nfs mounts? How do you handle this stuff? 

Thanks Martin!

PS: I gonna prepare a ansible role to setup a node/cluster - i hate doing repeatable tasks manually..

**Comment by ehazlett** [comment]
Hi!  As far as mounts, right now I use it as just a normal mount.  I make sure whatever NFS mounts that are needed are mounted ahead of time and then just use the mounted directory as the mount to the container.  I have been thinking _a lot_ about a cluster volume concept lately.  Nothing to report yet as I'm still experimenting :)

**Comment by mabunixda** [comment]
Thanks!
