### ISSUE TITLE
Supported arch(s)?

### ISSUE THREAD

**Issue by bndw** [ehazlett/stellar#27]
The Makefile is [hardcoded](https://github.com/ehazlett/stellar/blob/master/Makefile#L2) to use `amd64`. What are the chances this could be built for `arm`?

**Comment by ehazlett** [comment]
It works for ARM.  `make GOOS=linux GOARCH=arm` should give you arm binaries.

`bin/sctl: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped`

**Comment by ehazlett** [comment]
If demand is enough we could also add an ARM package to the releases.

**Comment by bndw** [comment]
Awesome, thanks!

**Comment by ehazlett** [comment]
Thanks for bringing this up.  I'm going to add a note in the README about different archs and look into autobuilding for releases.

**Comment by bndw** [comment]
I'd be interested in pre-compiled binaries and possibly contributing to that. Are you building your released manually right now, I don't see them in your travis config?

**Comment by ehazlett** [comment]
Awesome!  I've been working on Actions to automatically build and push to S3 as part of the regular releases.  I'll add an ARM target.

What would be awesome is feedback on how Stellar works on ARM and if there are any issues from the cross-compiled binaries.  If so, we might have to shift away from Actions.

Thanks!

**Comment by bndw** [comment]
I'll give it a test drive sometime over the next week and let you know if I run into any snags.

**Comment by bndw** [comment]
FYI, I hit [a snag](https://github.com/containerd/containerd/issues/2901) getting containerd on arm. Once I finish shaving that yak I can get started with stellar.

**Comment by ehazlett** [comment]
I was thinking about making ARM containerd builds available.  I can do that
if you think it will be useful :)

**Comment by bndw** [comment]
ARM containerd builds would be very useful. If you decide to do that, please also provide the Makefile/script so folks can run those builds themselves. Should that live in this repository or be upstreamed to containerd itself?

IMO the biggest hurdle I see is the lack of basic documentation for building containerd for ARM. Reducing that friction would help stellar users since it's a prereq.

**Comment by ehazlett** [comment]
It's actually super simple if you have an ARM device :)  Just `make`.  Cross compiling however is more difficult :)

I'll work to get CI building these but for now here is the latest master for armhf: https://s3.us-east-2.amazonaws.com/stellar-release/containerd/armhf/containerd-linux-armhf-e72ad44427f623a53c2d38c46598753d5e6fd63b.tar.gz
