### ISSUE TITLE
Fail-over?

### ISSUE THREAD

**Issue by jumbojett** [ehazlett/stellar#28]
Does stellar support fail-over? I'm able to deploy containers to specific nodes, but it's unclear how or if these get replicated or scaled.

Btw - Your video was very informative. Where can I find part II?
https://www.youtube.com/watch?v=diRmI45Yhg4

**Comment by ehazlett** [comment]
Currently the [scheduler](https://github.com/ehazlett/stellar/tree/master/services/scheduler#stellar-scheduler-service) does not monitor it simply schedules.  I'm planning a monitoring concept that will operate not just on state but also metrics to assist in re-scheduling in the event of a failure or other trigger (resource utilization, maintenance, etc).

As for the next parts, I haven't recorded it yet :)  I'll try to get some time soon to continue in the series :)
